# tf-changelog-releaser config
docs:
  directory: examples/tf-modules/docs/
changelog:
  name: CHANGELOG.md
  enabled: true
modules:
  directory: examples/tf-modules/modules
  docs_path: examples/tf-modules/docs/modules
